# Generated by Django 4.2.10 on 2024-02-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('identifiant', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
